import type { Settings, CostCategoryMeta, InvoicingSettings } from './types';

export const DEFAULT_INCOME_CATEGORIES = [
  'Consulting',
  'Development',
  'Design',
  'Writing',
  'Teaching',
  'Retainer',
  'Royalties',
  'Other Income',
];

export const DEFAULT_COST_CATEGORIES = [
  'Software & Tools',
  'Hardware & Equipment',
  'Office Supplies',
  'Travel',
  'Meals & Entertainment',
  'Professional Services',
  'Insurance',
  'Marketing & Advertising',
  'Education & Training',
  'Bank Fees',
  'Taxes & Licenses',
  'Utilities',
  'Rent',
  'Other Cost',
];

export const UK_COST_CATEGORIES = [
  'Software & Tools',
  'Hardware & Equipment',
  'Office Supplies',
  'Travel',
  'Vehicle / Mileage',
  'Meals & Entertainment',
  'Professional Services',
  'Accountancy Fees',
  'Insurance',
  'Marketing & Advertising',
  'Education & Training',
  'Bank Fees',
  'Taxes & Licenses',
  'Utilities',
  'Telephone & Internet',
  'Rent',
  'Use of Home',
  'Subscriptions & Memberships',
  'Fines & Penalties',
  'Other Cost',
];

export const DEFAULT_COST_CATEGORY_META: CostCategoryMeta[] = [
  { name: 'Software & Tools', allowable: 'yes' },
  { name: 'Hardware & Equipment', allowable: 'yes' },
  { name: 'Office Supplies', allowable: 'yes' },
  { name: 'Travel', allowable: 'yes' },
  { name: 'Vehicle / Mileage', allowable: 'yes' },
  { name: 'Meals & Entertainment', allowable: 'partial', note: 'Business meals only — client entertaining is not allowable' },
  { name: 'Professional Services', allowable: 'yes' },
  { name: 'Accountancy Fees', allowable: 'yes' },
  { name: 'Insurance', allowable: 'yes' },
  { name: 'Marketing & Advertising', allowable: 'yes' },
  { name: 'Education & Training', allowable: 'yes' },
  { name: 'Bank Fees', allowable: 'yes' },
  { name: 'Taxes & Licenses', allowable: 'yes' },
  { name: 'Utilities', allowable: 'yes' },
  { name: 'Telephone & Internet', allowable: 'partial', note: 'Business portion only' },
  { name: 'Rent', allowable: 'yes' },
  { name: 'Use of Home', allowable: 'yes' },
  { name: 'Subscriptions & Memberships', allowable: 'yes' },
  { name: 'Fines & Penalties', allowable: 'no' },
  { name: 'Other Cost', allowable: 'yes' },
];

export const defaultInvoicingSettings: InvoicingSettings = {
  bankDetails: '',
  defaultDailyRate: 0,
  defaultPaymentTerms: 30,
  defaultNotes: '',
  headerColor: '#ffffff',
  bodyColor: '#ffffff',
  filenameTemplate: '[businessname]-[issuedate]-[invoicenumber]',
  extraReferences: [],
};

export const defaultSettings: Settings = {
  businessName: '',
  businessAddress: '',
  email: '',
  phone: '',
  currencySymbol: '$',
  taxYear: 'calendar',
  taxMode: 'flat',
  taxRate: 0,
  incomeCategories: DEFAULT_INCOME_CATEGORIES,
  costCategories: DEFAULT_COST_CATEGORIES,
  costCategoryMeta: [],
  locale: 'en-US',
  vatRegistered: false,
  vatScheme: 'standard',
  vatFlatRate: 0,
  vatNumber: '',
  voluntaryClass2NI: false,
  studentLoanPlan: 'none',
  accountingBasis: 'cash',
  lastExportDate: null,
  invoicing: defaultInvoicingSettings,
};

export const STORAGE_KEYS = {
  settings: 'accounts.settings',
  transactions: 'accounts.transactions',
  clients: 'accounts.clients',
  invoices: 'accounts.invoices',
  onboardingDone: 'accounts.onboardingDone',
} as const;
