import { getDocument, GlobalWorkerOptions } from 'pdfjs-dist';

GlobalWorkerOptions.workerSrc = '/pdf.worker.min.mjs';

export type ParsedInvoice = {
  fileName: string;
  invoiceNumber: string;
  clientName: string;
  issueDate: string;
  amount: number;
  confidence: 'high' | 'medium' | 'low';
};

/**
 * Extract all text items from a PDF, reconstructing lines by Y position.
 */
async function extractLines(file: File): Promise<string[]> {
  const buffer = await file.arrayBuffer();
  const pdf = await getDocument({ data: buffer }).promise;
  console.log('[pdf-import] loaded PDF, pages:', pdf.numPages);
  const allLines: string[] = [];

  for (let p = 1; p <= pdf.numPages; p++) {
    const page = await pdf.getPage(p);
    const content = await page.getTextContent();

    console.log(`[pdf-import] page ${p} raw items:`, content.items.length);

    // Filter to items with actual text content
    const items: Array<{ str: string; transform: number[] }> = [];
    for (let idx = 0; idx < content.items.length; idx++) {
      const item = content.items[idx];
      if (item && 'str' in item && typeof (item as any).str === 'string' && (item as any).str.trim().length > 0) {
        items.push({ str: (item as any).str, transform: (item as any).transform });
      }
    }

    console.log(`[pdf-import] page ${p} text items after filter:`, items.length);

    // Sort by Y descending (top of page first), then X ascending
    items.sort((a, b) => {
      const yDiff = b.transform[5] - a.transform[5];
      if (Math.abs(yDiff) > 5) return yDiff;
      return a.transform[4] - b.transform[4];
    });

    let currentY = -1;
    let currentLine = '';
    for (let idx = 0; idx < items.length; idx++) {
      const item = items[idx];
      const y = Math.round(item.transform[5]);
      if (currentY === -1 || Math.abs(y - currentY) > 5) {
        if (currentLine.trim()) allLines.push(currentLine.trim());
        currentLine = item.str;
        currentY = y;
      } else {
        currentLine += '  ' + item.str;
      }
    }
    if (currentLine.trim()) allLines.push(currentLine.trim());
  }

  return allLines;
}

/**
 * Try to parse a date string. Returns ISO YYYY-MM-DD or empty string.
 */
export function parseDate(raw: string): string {
  if (!raw) return '';
  const trimmed = raw.trim();

  if (/^\d{4}-\d{2}-\d{2}$/.test(trimmed)) return trimmed;

  // Parse with explicit UTC noon to avoid timezone day-shift
  const d = new Date(trimmed + ' UTC');
  if (!isNaN(d.getTime())) {
    return d.toISOString().split('T')[0];
  }
  // Fallback without UTC suffix
  const d2 = new Date(trimmed);
  if (!isNaN(d2.getTime())) {
    const year = d2.getFullYear();
    const month = String(d2.getMonth() + 1).padStart(2, '0');
    const day = String(d2.getDate()).padStart(2, '0');
    return `${year}-${month}-${day}`;
  }

  const dmy = /^(\d{1,2})[/\-.](\d{1,2})[/\-.](\d{4})$/.exec(trimmed);
  if (dmy) {
    const [, day, month, year] = dmy;
    return `${year}-${month.padStart(2, '0')}-${day.padStart(2, '0')}`;
  }

  return '';
}

/**
 * Extract a currency amount from a string like "$1,234.56" or "£500.00"
 */
export function parseAmount(raw: string): number {
  if (!raw) return 0;
  const cleaned = raw.replace(/[^0-9.]/g, '');
  const num = parseFloat(cleaned);
  return isNaN(num) ? 0 : num;
}

/**
 * Extract invoice number from filename as fallback.
 */
export function invoiceNumberFromFilename(name: string): string {
  const base = name.replace(/\.pdf$/i, '');

  const invMatch = /\b(INV[.\-_]?\d+)\b/i.exec(base);
  if (invMatch) return invMatch[1];

  const parts = base.split(/[-_]/);
  if (parts.length > 1) {
    const last = parts[parts.length - 1];
    if (/\d/.test(last)) return last;
  }

  return base;
}

/**
 * Lines that are table headers, table data, or boilerplate — skip when looking for client name.
 */
const TABLE_HEADER_PATTERN = /^(Description|Start|End|Days|Daily\s*rate|Total|Date|Notes|Amount|Work\s*sub|Expenses|Grand\s*total|Page\s*\d)/i;

/**
 * Invoicer calendar tooltip text and other boilerplate that appears after Bill To
 * when no client name is filled in.
 */
const BOILERPLATE_PATTERN = /^(Only Monday|Monday.Friday|count towards|towards totals|Weekends are|skipped automatically|automatically)/i;

/**
 * Parse a PDF generated by the invoicer app.
 * The invoicer places left-column content (business info, Bill To) and right-column
 * content (Invoice Details) at the same Y position, so they merge into single lines.
 * We use patterns that match labels mid-line.
 */
export async function parseInvoicePdf(file: File): Promise<ParsedInvoice> {
  const result: ParsedInvoice = {
    fileName: file.name,
    invoiceNumber: '',
    clientName: '',
    issueDate: '',
    amount: 0,
    confidence: 'low',
  };

  let lines: string[];
  try {
    lines = await extractLines(file);
  } catch (e) {
    console.warn('[pdf-import] extraction FAILED for', file.name, e);
    result.invoiceNumber = invoiceNumberFromFilename(file.name);
    return result;
  }

  console.log(`[pdf-import] ${file.name} — ${lines.length} lines extracted:`);
  lines.forEach((l, i) => console.log(`  [${i}] ${l}`));

  if (lines.length === 0) {
    result.invoiceNumber = invoiceNumberFromFilename(file.name);
    return result;
  }

  let fieldsFound = 0;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];

    // Invoice number: appears as "...  Invoice #:  15" (value follows label, possibly mid-line)
    if (!result.invoiceNumber) {
      const m = /Invoice\s*#\s*:\s*(.+)/i.exec(line);
      if (m) {
        const val = m[1].trim().replace(/\s{2,}.*$/, '');
        if (val && val !== '—' && val !== '-') {
          result.invoiceNumber = val;
          fieldsFound++;
        }
      }
    }

    // Invoice date: appears as "...  Invoice date:  Nov 19, 2025"
    if (!result.issueDate) {
      const m = /Invoice\s*date\s*:\s*(.+)/i.exec(line);
      if (m) {
        const raw = m[1].trim().replace(/\s{2,}.*$/, '');
        const parsed = parseDate(raw);
        if (parsed) {
          result.issueDate = parsed;
          fieldsFound++;
        }
      }
    }

    // Client name: after "Bill To" label, skip table headers and work item rows
    if (!result.clientName && /Bill\s*To/i.test(line)) {
      for (let j = i + 1; j < lines.length && j <= i + 5; j++) {
        const next = lines[j]?.trim();
        if (!next) continue;
        if (TABLE_HEADER_PATTERN.test(next)) continue;
        if (BOILERPLATE_PATTERN.test(next)) continue;
        if (/\d{4}\s+[£$€]/.test(next)) continue;
        if (/^Work\b/i.test(next)) continue;
        // Skip expense-related lines
        if (/^(Nov|Dec|Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct)\s+\d/i.test(next)) continue;
        const clientPart = next.split(/\s{2,}/)[0];
        if (clientPart && clientPart.length > 1) {
          result.clientName = clientPart;
          fieldsFound++;
        }
        break;
      }
    }

    // Grand total: "Grand total  £6124.00"
    if (!result.amount) {
      const m = /Grand\s*total\s+(.+)/i.exec(line);
      if (m) {
        result.amount = parseAmount(m[1]);
        if (result.amount > 0) fieldsFound++;
      }
    }
  }

  // Fallback: invoice number from filename
  if (!result.invoiceNumber) {
    result.invoiceNumber = invoiceNumberFromFilename(file.name);
  }

  if (fieldsFound >= 3) result.confidence = 'high';
  else if (fieldsFound >= 1) result.confidence = 'medium';

  console.log(`[pdf-import] ${file.name} result:`, result);
  return result;
}

/**
 * Parse multiple PDF files in parallel.
 */
export async function parseInvoicePdfs(files: File[]): Promise<ParsedInvoice[]> {
  return Promise.all(files.map(parseInvoicePdf));
}
