import { GlobalWorkerOptions, getDocument } from 'pdfjs-dist';
import type { TextItem } from 'pdfjs-dist/types/src/display/api';

// Use the bundled worker
GlobalWorkerOptions.workerSrc = new URL(
  'pdfjs-dist/build/pdf.worker.min.mjs',
  import.meta.url
).toString();

export type ParsedInvoice = {
  fileName: string;
  invoiceNumber: string;
  clientName: string;
  issueDate: string;
  amount: number;
  confidence: 'high' | 'medium' | 'low';
};

/**
 * Extract all text items from a PDF file, preserving rough position info.
 * Returns lines grouped by approximate Y position on each page.
 */
async function extractText(file: File): Promise<string[]> {
  const buffer = await file.arrayBuffer();
  const pdf = await getDocument({ data: buffer }).promise;
  const allLines: string[] = [];

  for (let p = 1; p <= pdf.numPages; p++) {
    const page = await pdf.getPage(p);
    const content = await page.getTextContent();

    // Group text items by approximate Y position to reconstruct lines
    const items = content.items.filter(
      (item): item is TextItem => 'str' in item && item.str.trim().length > 0
    );

    // Sort by Y (descending, since PDF Y is bottom-up) then X
    const sorted = items.sort((a, b) => {
      const yDiff = b.transform[5] - a.transform[5];
      if (Math.abs(yDiff) > 5) return yDiff;
      return a.transform[4] - b.transform[4];
    });

    let currentY = -1;
    let currentLine = '';
    for (const item of sorted) {
      const y = Math.round(item.transform[5]);
      if (currentY === -1 || Math.abs(y - currentY) > 5) {
        if (currentLine.trim()) allLines.push(currentLine.trim());
        currentLine = item.str;
        currentY = y;
      } else {
        // Items on the same line — add spacing if there's a gap
        currentLine += '  ' + item.str;
      }
    }
    if (currentLine.trim()) allLines.push(currentLine.trim());
  }

  return allLines;
}

/**
 * Try to parse a date string in various formats the invoicer might produce.
 * Returns ISO date string (YYYY-MM-DD) or empty string.
 */
function parseDate(raw: string): string {
  if (!raw) return '';
  const trimmed = raw.trim();

  // Already ISO
  if (/^\d{4}-\d{2}-\d{2}$/.test(trimmed)) return trimmed;

  // Try native Date parsing (handles "1 Jan 2025", "Jan 1, 2025", etc.)
  const d = new Date(trimmed);
  if (!isNaN(d.getTime())) {
    return d.toISOString().split('T')[0];
  }

  // DD/MM/YYYY or DD-MM-YYYY
  const dmy = /^(\d{1,2})[/\-.](\d{1,2})[/\-.](\d{4})$/.exec(trimmed);
  if (dmy) {
    const [, day, month, year] = dmy;
    return `${year}-${month.padStart(2, '0')}-${day.padStart(2, '0')}`;
  }

  return '';
}

/**
 * Extract a currency amount from a string like "$1,234.56" or "£500.00"
 */
function parseAmount(raw: string): number {
  if (!raw) return 0;
  // Strip currency symbols and commas, keep digits and dots
  const cleaned = raw.replace(/[^0-9.]/g, '');
  const num = parseFloat(cleaned);
  return isNaN(num) ? 0 : num;
}

/**
 * Extract invoice number from filename as fallback.
 * Common patterns: "CompanyName-2025-01-15-INV001.pdf", "INV-001.pdf"
 */
function invoiceNumberFromFilename(name: string): string {
  // Remove extension
  const base = name.replace(/\.pdf$/i, '');

  // Look for INV-xxx or similar patterns
  const invMatch = /\b(INV[.\-_]?\d+)\b/i.exec(base);
  if (invMatch) return invMatch[1];

  // Last segment after a dash might be the invoice number
  const parts = base.split(/[-_]/);
  if (parts.length > 1) {
    const last = parts[parts.length - 1];
    if (/\d/.test(last)) return last;
  }

  return base;
}

/**
 * Parse a PDF generated by the invoicer app.
 * Looks for known labels like "Invoice #:", "Invoice date:", "Grand total", "Bill To"
 */
export async function parseInvoicePdf(file: File): Promise<ParsedInvoice> {
  const result: ParsedInvoice = {
    fileName: file.name,
    invoiceNumber: '',
    clientName: '',
    issueDate: '',
    amount: 0,
    confidence: 'low',
  };

  let lines: string[];
  try {
    lines = await extractText(file);
  } catch {
    // Text extraction failed entirely — use filename only
    result.invoiceNumber = invoiceNumberFromFilename(file.name);
    return result;
  }

  if (lines.length === 0) {
    result.invoiceNumber = invoiceNumberFromFilename(file.name);
    return result;
  }

  let fieldsFound = 0;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];

    // Invoice number: "Invoice #:  INV-001" or on the same line after the label
    if (!result.invoiceNumber) {
      const invMatch = /Invoice\s*#\s*:\s*(.+)/i.exec(line);
      if (invMatch) {
        result.invoiceNumber = invMatch[1].trim().replace(/\s{2,}.*$/, '');
        fieldsFound++;
        continue;
      }
    }

    // Invoice date: "Invoice date:  1 Jan 2025"
    if (!result.issueDate) {
      const dateMatch = /Invoice\s*date\s*:\s*(.+)/i.exec(line);
      if (dateMatch) {
        const raw = dateMatch[1].trim().replace(/\s{2,}.*$/, '');
        result.issueDate = parseDate(raw);
        if (result.issueDate) fieldsFound++;
        continue;
      }
    }

    // Client name: line(s) after "Bill To"
    if (!result.clientName && /^Bill\s*To$/i.test(line.trim())) {
      // Next non-empty line is the client name
      for (let j = i + 1; j < lines.length && j <= i + 3; j++) {
        const next = lines[j]?.trim();
        if (next && !/^(Description|Start|End|Days|Daily)/i.test(next)) {
          result.clientName = next;
          fieldsFound++;
          break;
        }
      }
      continue;
    }

    // Grand total: "Grand total  $1,234.56"
    if (!result.amount) {
      const totalMatch = /Grand\s*total\s+(.+)/i.exec(line);
      if (totalMatch) {
        result.amount = parseAmount(totalMatch[1]);
        if (result.amount > 0) fieldsFound++;
        continue;
      }
    }
  }

  // Fallback: invoice number from filename
  if (!result.invoiceNumber) {
    result.invoiceNumber = invoiceNumberFromFilename(file.name);
  }

  // Set confidence based on how many fields we extracted
  if (fieldsFound >= 3) result.confidence = 'high';
  else if (fieldsFound >= 1) result.confidence = 'medium';

  return result;
}

/**
 * Parse multiple PDF files in parallel.
 */
export async function parseInvoicePdfs(files: File[]): Promise<ParsedInvoice[]> {
  return Promise.all(files.map(parseInvoicePdf));
}
