import * as pdfjsLib from 'pdfjs-dist';

// Use a self-hosted worker copied to public/ to avoid CDN version mismatches
pdfjsLib.GlobalWorkerOptions.workerSrc = '/pdf.worker.min.mjs';

export type ParsedInvoice = {
  fileName: string;
  invoiceNumber: string;
  clientName: string;
  issueDate: string;
  amount: number;
  confidence: 'high' | 'medium' | 'low';
};

/**
 * Extract all text items from a PDF, reconstructing lines by Y position.
 */
async function extractLines(file: File): Promise<string[]> {
  const buffer = await file.arrayBuffer();
  const pdf = await pdfjsLib.getDocument({ data: buffer }).promise;
  const allLines: string[] = [];

  for (let p = 1; p <= pdf.numPages; p++) {
    const page = await pdf.getPage(p);
    const content = await page.getTextContent();

    // Filter to items with actual text content
    const items: Array<{ str: string; transform: number[] }> = [];
    for (const item of content.items) {
      if ('str' in item && typeof item.str === 'string' && item.str.trim().length > 0) {
        items.push(item as { str: string; transform: number[] });
      }
    }

    // Sort by Y descending (top of page first), then X ascending
    items.sort((a, b) => {
      const yDiff = b.transform[5] - a.transform[5];
      if (Math.abs(yDiff) > 5) return yDiff;
      return a.transform[4] - b.transform[4];
    });

    let currentY = -1;
    let currentLine = '';
    for (const item of items) {
      const y = Math.round(item.transform[5]);
      if (currentY === -1 || Math.abs(y - currentY) > 5) {
        if (currentLine.trim()) allLines.push(currentLine.trim());
        currentLine = item.str;
        currentY = y;
      } else {
        currentLine += '  ' + item.str;
      }
    }
    if (currentLine.trim()) allLines.push(currentLine.trim());
  }

  return allLines;
}

/**
 * Try to parse a date string. Returns ISO YYYY-MM-DD or empty string.
 */
function parseDate(raw: string): string {
  if (!raw) return '';
  const trimmed = raw.trim();

  if (/^\d{4}-\d{2}-\d{2}$/.test(trimmed)) return trimmed;

  const d = new Date(trimmed);
  if (!isNaN(d.getTime())) {
    return d.toISOString().split('T')[0];
  }

  const dmy = /^(\d{1,2})[/\-.](\d{1,2})[/\-.](\d{4})$/.exec(trimmed);
  if (dmy) {
    const [, day, month, year] = dmy;
    return `${year}-${month.padStart(2, '0')}-${day.padStart(2, '0')}`;
  }

  return '';
}

/**
 * Extract a currency amount from a string like "$1,234.56" or "£500.00"
 */
function parseAmount(raw: string): number {
  if (!raw) return 0;
  const cleaned = raw.replace(/[^0-9.]/g, '');
  const num = parseFloat(cleaned);
  return isNaN(num) ? 0 : num;
}

/**
 * Extract invoice number from filename as fallback.
 */
function invoiceNumberFromFilename(name: string): string {
  const base = name.replace(/\.pdf$/i, '');

  const invMatch = /\b(INV[.\-_]?\d+)\b/i.exec(base);
  if (invMatch) return invMatch[1];

  const parts = base.split(/[-_]/);
  if (parts.length > 1) {
    const last = parts[parts.length - 1];
    if (/\d/.test(last)) return last;
  }

  return base;
}

/**
 * Lines that are table headers or table data — skip these when looking for client name.
 */
const TABLE_HEADER_PATTERN = /^(Description|Start|End|Days|Daily\s*rate|Total|Date|Notes|Amount|Work\s*sub|Expenses|Grand\s*total|Page\s*\d)/i;

/**
 * Parse a PDF generated by the invoicer app.
 * The invoicer places left-column content (business info, Bill To) and right-column
 * content (Invoice Details) at the same Y position, so they merge into single lines.
 * We use patterns that match labels mid-line.
 */
export async function parseInvoicePdf(file: File): Promise<ParsedInvoice> {
  const result: ParsedInvoice = {
    fileName: file.name,
    invoiceNumber: '',
    clientName: '',
    issueDate: '',
    amount: 0,
    confidence: 'low',
  };

  let lines: string[];
  try {
    lines = await extractLines(file);
  } catch (e) {
    console.warn('PDF text extraction failed for', file.name, e);
    result.invoiceNumber = invoiceNumberFromFilename(file.name);
    return result;
  }

  if (lines.length === 0) {
    result.invoiceNumber = invoiceNumberFromFilename(file.name);
    return result;
  }

  let fieldsFound = 0;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];

    // Invoice number: appears as "...  Invoice #:  15" (value follows label, possibly mid-line)
    if (!result.invoiceNumber) {
      const m = /Invoice\s*#\s*:\s*(.+)/i.exec(line);
      if (m) {
        // Take the first token after the label, strip trailing merged content
        let val = m[1].trim().replace(/\s{2,}.*$/, '');
        if (val && val !== '—' && val !== '-') {
          result.invoiceNumber = val;
          fieldsFound++;
        }
      }
    }

    // Invoice date: appears as "...  Invoice date:  Nov 19, 2025"
    if (!result.issueDate) {
      const m = /Invoice\s*date\s*:\s*(.+)/i.exec(line);
      if (m) {
        // The date value may be followed by other merged text
        let raw = m[1].trim().replace(/\s{2,}.*$/, '');
        const parsed = parseDate(raw);
        if (parsed) {
          result.issueDate = parsed;
          fieldsFound++;
        }
      }
    }

    // Client name: after "Bill To" label, skip table headers and work item rows
    if (!result.clientName && /Bill\s*To/i.test(line)) {
      for (let j = i + 1; j < lines.length && j <= i + 5; j++) {
        const next = lines[j]?.trim();
        if (!next) continue;
        // Skip table headers, work rows (start with date-like patterns), and known labels
        if (TABLE_HEADER_PATTERN.test(next)) continue;
        // Skip lines that look like work item rows (contain currency amounts mid-line)
        if (/\d{4}\s+[£$€]/.test(next)) continue;
        // Skip lines that look like "Work  Nov 01, 2025  ..."
        if (/^Work\b/i.test(next)) continue;
        // This looks like a client name
        // If it contains double-spaces, take only the first segment (left column)
        const clientPart = next.split(/\s{2,}/)[0];
        if (clientPart && clientPart.length > 1) {
          result.clientName = clientPart;
          fieldsFound++;
        }
        break;
      }
    }

    // Grand total: "Grand total  £6124.00"
    if (!result.amount) {
      const m = /Grand\s*total\s+(.+)/i.exec(line);
      if (m) {
        result.amount = parseAmount(m[1]);
        if (result.amount > 0) fieldsFound++;
      }
    }
  }

  // Fallback: invoice number from filename
  if (!result.invoiceNumber) {
    result.invoiceNumber = invoiceNumberFromFilename(file.name);
  }

  if (fieldsFound >= 3) result.confidence = 'high';
  else if (fieldsFound >= 1) result.confidence = 'medium';

  return result;
}

/**
 * Parse multiple PDF files in parallel.
 */
export async function parseInvoicePdfs(files: File[]): Promise<ParsedInvoice[]> {
  return Promise.all(files.map(parseInvoicePdf));
}
